### ISSUE TITLE
Termination Analysis leads to ModuleNotFoundError: No module named 'z3'

### ISSUE THREAD

**Issue by shaunazzopardi** [seahorn/seahorn#524]
**Describe the bug**
Attempting to perform termination analysis of a .c file leads to a ModuleNotFoundError: No module named 'z3' error.

**To Reproduce**

The input file is: 

```
int main(int cnt){
	while(cnt >= 0){
		cnt = cnt - 1;
	}
	sassert(cnt > 0);
}
```

The steps I took are the following:

```
docker pull seahorn/seahorn-llvm14:nightly
docker run -v <path>\prog.c:/prog.c --rm -it seahorn/seahorn-llvm14:nightly
sea term /prog.c
```

Then I get the following output:

```
/usr/bin/clang-14 -c -emit-llvm -D__SEAHORN__ -fdeclspec -O1 -Xclang -disable-llvm-optzns -fgnu89-inline -m32 -I/home/usea/seahorn/include -o /tmp/sea-dea60xzp/prog.bc /prog.c
/prog.c:2:5: warning: only one parameter on 'main' declaration [-Wmain]
int main(int cnt){
    ^
/prog.c:7:2: warning: implicit declaration of function 'sassert' is invalid in C99 [-Wimplicit-function-declaration]
        sassert(cnt > 0);
        ^
2 warnings generated.
/home/usea/seahorn/bin/seapp -o /tmp/sea-dea60xzp/prog.pp.bc --simplifycfg-sink-common=false --strip-extern=false --promote-assumptions=false --kill-vaarg=true --ignore-def-verifier-fn=false --horn-keep-arith-overflow=false --promote-nondet-undef=true --horn-replace-loops-with-nd-funcs=false /tmp/sea-dea60xzp/prog.bc
/home/usea/seahorn/bin/seapp --simplifycfg-sink-common=false -o /tmp/sea-dea60xzp/prog.pp.ms.bc --horn-mixed-sem --ms-reduce-main /tmp/sea-dea60xzp/prog.pp.bc
/home/usea/seahorn/bin/seaopt -f --simplifycfg-sink-common=false -o /tmp/sea-dea60xzp/prog.pp.ms.o.bc -O3 --seaopt-enable-indvar=false --seaopt-enable-loop-idiom=false --unroll-threshold=150 --unroll-allow-partial=false --unroll-partial-threshold=0 --vectorize-slp=false /tmp/sea-dea60xzp/prog.pp.ms.bc
/home/usea/seahorn/bin/seahorn --keep-shadows=true --sea-dsa=ci -horn-inter-proc -horn-sem-lvl=mem --horn-step=large -o /tmp/sea-dea60xzp/prog.pp.ms.o.smt2 /tmp/sea-dea60xzp/prog.pp.ms.o.bc
WARNING: no assertion was found so either program does not have assertions or frontend discharged them.
Traceback (most recent call last):
  File "/home/usea/seahorn/lib/seapy/sea/commands.py", line 1500, in run
    import term.termination as tt
  File "/home/usea/seahorn/lib/seapy/term/termination.py", line 6, in <module>
    import z3
ModuleNotFoundError: No module named 'z3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usea/seahorn/bin/sea", line 74, in <module>
    sys.exit (main (sys.argv[1:]))
  File "/home/usea/seahorn/bin/sea", line 56, in main
    return cmd.main (argv)
  File "/home/usea/seahorn/lib/seapy/sea/core.py", line 184, in main
    return self.run (args, extra)
  File "/home/usea/seahorn/lib/seapy/sea/core.py", line 216, in run
    return args.func(args, extra)
  File "/home/usea/seahorn/lib/seapy/sea/core.py", line 289, in run
    res = c.main (argv)
  File "/home/usea/seahorn/lib/seapy/sea/core.py", line 184, in main
    return self.run (args, extra)
  File "/home/usea/seahorn/lib/seapy/sea/commands.py", line 1503, in run
    raise IOError(str(e))
OSError: No module named 'z3'
```

**Additional context**
z3 seems to be available on the path in the docker container.

**Comment by agurfinkel** [comment]
Termination analysis has not been maintained and might not work with the latest version of seahorn.

We would appreciate if you are able to fix the scripts to work.
The two errors that you are running into seem to be
1. `seahorn/seahorn.h` is not in the include path, so `sassert` is not expanded properly
2. `z3` python package in not installed in docker, but the script relies on it
