### ISSUE TITLE
argparse error after successful local build

### ISSUE THREAD

**Issue by shashinh** [seahorn/seahorn#558]
Hello! I'm setting up a local developer build of Seahorn, which went well (using the `dev14` branch). However, I see the following error on a sanity check after the fact.

```
$ sea --help
Traceback (most recent call last):
  File "/home/shashin/projects/seahorn/gh-dev-14/seahorn/build/run/bin/sea", line 74, in <module>
    sys.exit (main (sys.argv[1:]))
              ^^^^^^^^^^^^^^^^^^^
  File "/home/shashin/projects/seahorn/gh-dev-14/seahorn/build/run/bin/sea", line 56, in main
    return cmd.main (argv)
           ^^^^^^^^^^^^^^^
  File "/home/shashin/projects/seahorn/gh-dev-14/seahorn/build/run/lib/seapy/sea/core.py", line 177, in main
    ap = self.mk_arg_parser (ap)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shashin/projects/seahorn/gh-dev-14/seahorn/build/run/lib/seapy/sea/core.py", line 210, in mk_arg_parser
    sp = sb.add_parser(c.name, help=c.help, add_help=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 1219, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument parser: conflicting subparser: smc

```

The build seems alright since the other binaries appear intact:
```
$ seahorn --help
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
OVERVIEW: SeaHorn -- LLVM bitcode to Horn/SMT2 transformation

USAGE: seahorn [options] <input LLVM bitcode file>
...
```

**Comment by agurfinkel** [comment]
This seems related to new features of python 3.12. Can you use an earlier version of Python?

**Comment by shashinh** [comment]
Suspected as much. Switching to 3.10.4 did the trick. Thank you!
